services:
  - type: web
    name: ai-adaptlearn
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python launch.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    branch: main
    rootDir: .
    dockerfilePath: ./Dockerfile
